# Generated by Django 2.0.2 on 2020-06-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200617_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('TR', 'Travel'), ('LI', 'Lifestyle'), ('PH', 'Photography'), ('CU', 'Culinary'), ('FA', 'Fashion'), ('WO', 'Work'), ('BU', 'Business')], max_length=2, null=True),
        ),
    ]
