# Generated by Django 2.0.2 on 2020-06-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TR', 'Travel'), ('LI', 'Lifestyle'), ('PH', 'Photography'), ('CU', 'Culinary'), ('FA', 'Fashion'), ('WO', 'Work'), ('BU', 'Business')], max_length=2),
        ),
    ]
