# Generated by Django 2.0.2 on 2020-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200617_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Lifestyle', 'Lifestyle'), ('Photography', 'Photography'), ('Culinary', 'Culinary'), ('Fashion', 'Fashion'), ('Work', 'Work'), ('Business', 'Business')], max_length=10),
        ),
    ]
