# Generated by Django 4.0 on 2021-12-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_post_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Travel', 'Travel'), ('Lifestyle', 'Lifestyle'), ('Photography', 'Photography'), ('Culinary', 'Culinary'), ('Fashion', 'Fashion'), ('Work', 'Work'), ('Business', 'Business')], max_length=20),
        ),
    ]
